### ISSUE TITLE
testgrid.k8s.io does not set the 'message' field on failing tests

### ISSUE THREAD

**Issue by smarterclayton** [GoogleCloudPlatform/testgrid#109]
The open source updater sets `message` on failing tests at https://github.com/GoogleCloudPlatform/testgrid/blob/master/pkg/updater/updater.go#L81, but on testgrid.k8s.io I don't see any result (the json is empty).  I'm assuming that this is due to the field not being read by the closed-source updater.

This means that the alert summary page isn't as useful as it could be because we only get the failing test, not the message, which means a lot more clicks to get at the root cause.  It would also be useful for re-mixing the testgrid output into higher level triage forms.

Expected result: `message` is set on failing tests to the first 140 characters of the failure entry in a junit on testgrid.k8s.io

**Comment by fejta** [comment]
This will be fixed in a future release (by starting to use the open source updater).

This will remain an issue when all the following are true:
* Hover over a cell and you see a message
* The row for that cell is red (aka the row is alerting)
* Expanding the summary tab's alerts for this row does not show any messages.





If you compare:
* https://external-canary-dot-k8s-testgrid.appspot.com/sig-release-1.17-informing#gce-windows-1.17
* https://external-canary-dot-k8s-testgrid.appspot.com/sig-release-1.17-informing#gce-windows-1.17&grid=beta

You will notice that this tab has a handful of broken rows, for example:
* `Kubernetes e2e suite.[sig-network] Services should be able to create a functioning NodePort service [Conformance]`.

If you mouse over this row on the `&grid=beta` link you will see it shows a truncated version of the error message from the [build log](https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/ci-kubernetes-e2e-windows-gce-1-17/1289798489861001217):
* ```
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/framework/framework.go:721
Aug  2 06:11:14.546: Unexpected error:
    <*errors.errorString | 0xc0004fc310>: {
        s: "service is not reachable within 2m0s timeout on endpoint nodeport-test:80 over TCP protocol",
    }
    service is not reachable within 2m0s timeout on endpoint nodeport-test:80 over TCP protocol
occurred
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/network/service.go:599
```

That means that the grid state proto created by the open source updater sets the message field, which should cause it to get plumbed through the rest of the system once we start using it (soon TM)
